name: MacOS SSH to GitHub Actions

on:
  push:
    branches: [ macworks ]
    paths-ignore: 'README.md'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ssh:
    runs-on: macos-10.15

    env:
      GitHubName: "rokibhasansagar"

    steps:
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email ${{ secrets.GitHubMail }}
        git config --global user.name ${GitHubName}
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: System Specs
      run: |
        system_profiler SPHardwareDataType
        echo -e "\n\n"
        df -h
    - name: SSH Keepalive
      run: |
        curl -sL https://gist.github.com/rokibhasansagar/077b66b16cd50e50e5ad9489084dc926/raw/ssh_keepalive.sh | bash
    - name: SSH connection to Actions
      continue-on-error: true
      timeout-minutes: 340
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: eu
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    - name: Self Looping
      run: |
        git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} -b macworks loop
        cd loop || exit 1
        echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
        git add looper.txt
        git commit -m "Looping at $(date -u +%D-%T%P)"
        git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:macworks
