name: MacOS SSH to GitHub Actions

on:
  push:
    branches: [ mac ]
    paths-ignore: 'README.md'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ssh:
    runs-on: macos-11.0

    env:
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"

    steps:
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email ${GitHubMail}
        git config --global user.name ${GitHubName}
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: System Specs
      run: system_profiler SPHardwareDataType
    - name: SSH Keepalive
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no
        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
    - name: Minor cleanups
      run: |
        brew uninstall -f --cask adoptopenjdk11 adoptopenjdk8 chromedriver firefox google-chrome julia microsoft-auto-update microsoft-edge session-manager-plugin
        brew uninstall -f --formula aliyun-cli ant aspell aws-sam-cli azure-cli bazelisk carthage composer fontconfig freetds freetype gcc@8 gd geckodriver gh gradle helm hub jpeg libpq libtiff llvm maven mongodb-community mongodb-database-tools node@14 openjdk php pipx postgresql python@3.8 rustup-init selenium-server-standalone subversion tidy-html5 unixodbc webp
    - name: Setup GNU Tools
      run: |
        git clone https://github.com/fabiomaia/linuxify.git
        cd linuxify/
        echo n | ./linuxify install
        cd .. && rm -rf linuxify
        echo ". ~/.linuxify" >> ~/.bashrc && . ~/.bashrc
        echo ". ~/.linuxify" >> ~/.zshrc && . ~/.zshrc
    - name: Test bash
      run: |
        sudo sed -i 's#^/bin/bash$#/usr/local/bin/bash#' /etc/shells
        bash --version | grep bash
    - name: SSH connection to Actions
      continue-on-error: true
      timeout-minutes: 340
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: eu
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    - name: Self Looping
      run: |
        git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} -b mac loop
        cd loop || exit 1
        echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
        git add looper.txt
        git commit -m "Looping at $(date -u +%D-%T%P)"
        git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:mac
